// Frozen catalog 2. Add a new version to change pools or geometry.
import type { BakedCut } from './bakedCut';
import type { BakedCutLibrary } from './bakedCutLibrary';

export const BAKED_CUT_LIBRARY_V2: BakedCutLibrary = {
  "amoeba-columnar": {
    "10x10": [require("../../../../assets/cuts-v2/amoeba-columnar/10x10/0.json") as BakedCut, require("../../../../assets/cuts-v2/amoeba-columnar/10x10/1.json") as BakedCut],
    "14x14": [require("../../../../assets/cuts-v2/amoeba-columnar/14x14/0.json") as BakedCut, require("../../../../assets/cuts-v2/amoeba-columnar/14x14/1.json") as BakedCut],
    "3x3": [require("../../../../assets/cuts/amoeba-columnar/3x3/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/3x3/1.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/3x3/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/3x3/3.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/3x3/4.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/3x3/5.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/3x3/6.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/3x3/7.json") as BakedCut],
    "4x4": [require("../../../../assets/cuts/amoeba-columnar/4x4/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/4x4/1.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/4x4/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/4x4/3.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/4x4/4.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/4x4/5.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/4x4/6.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/4x4/7.json") as BakedCut],
    "5x5": [require("../../../../assets/cuts/amoeba-columnar/5x5/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/5x5/1.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/5x5/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/5x5/3.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/5x5/4.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/5x5/5.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/5x5/6.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/5x5/7.json") as BakedCut],
    "7x7": [require("../../../../assets/cuts/amoeba-columnar/7x7/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/7x7/1.json") as BakedCut, require("../../../../assets/cuts-v2/amoeba-columnar/7x7/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-columnar/7x7/3.json") as BakedCut],
  },
  "amoeba-coral": {
    "10x10": [require("../../../../assets/cuts-v2/amoeba-coral/10x10/0.json") as BakedCut, require("../../../../assets/cuts-v2/amoeba-coral/10x10/1.json") as BakedCut],
    "14x14": [require("../../../../assets/cuts-v2/amoeba-coral/14x14/0.json") as BakedCut, require("../../../../assets/cuts-v2/amoeba-coral/14x14/1.json") as BakedCut],
    "3x3": [require("../../../../assets/cuts/amoeba-coral/3x3/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/3x3/1.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/3x3/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/3x3/3.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/3x3/4.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/3x3/5.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/3x3/6.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/3x3/7.json") as BakedCut],
    "4x4": [require("../../../../assets/cuts/amoeba-coral/4x4/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/4x4/1.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/4x4/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/4x4/3.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/4x4/4.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/4x4/5.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/4x4/6.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/4x4/7.json") as BakedCut],
    "5x5": [require("../../../../assets/cuts/amoeba-coral/5x5/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/5x5/1.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/5x5/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/5x5/3.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/5x5/4.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/5x5/5.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/5x5/6.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/5x5/7.json") as BakedCut],
    "7x7": [require("../../../../assets/cuts/amoeba-coral/7x7/0.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/7x7/1.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/7x7/2.json") as BakedCut, require("../../../../assets/cuts/amoeba-coral/7x7/3.json") as BakedCut],
  },
  "crystal-four": {
    "10x10": [require("../../../../assets/cuts-v2/crystal-four/10x10/0.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-four/10x10/1.json") as BakedCut],
    "14x14": [require("../../../../assets/cuts-v2/crystal-four/14x14/0.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-four/14x14/1.json") as BakedCut],
    "3x3": [require("../../../../assets/cuts/crystal-four/3x3/0.json") as BakedCut, require("../../../../assets/cuts/crystal-four/3x3/1.json") as BakedCut, require("../../../../assets/cuts/crystal-four/3x3/2.json") as BakedCut, require("../../../../assets/cuts/crystal-four/3x3/3.json") as BakedCut, require("../../../../assets/cuts/crystal-four/3x3/4.json") as BakedCut, require("../../../../assets/cuts/crystal-four/3x3/5.json") as BakedCut, require("../../../../assets/cuts/crystal-four/3x3/6.json") as BakedCut, require("../../../../assets/cuts/crystal-four/3x3/7.json") as BakedCut],
    "4x4": [require("../../../../assets/cuts/crystal-four/4x4/0.json") as BakedCut, require("../../../../assets/cuts/crystal-four/4x4/1.json") as BakedCut, require("../../../../assets/cuts/crystal-four/4x4/2.json") as BakedCut, require("../../../../assets/cuts/crystal-four/4x4/3.json") as BakedCut, require("../../../../assets/cuts/crystal-four/4x4/4.json") as BakedCut, require("../../../../assets/cuts/crystal-four/4x4/5.json") as BakedCut, require("../../../../assets/cuts/crystal-four/4x4/6.json") as BakedCut, require("../../../../assets/cuts/crystal-four/4x4/7.json") as BakedCut],
    "5x5": [require("../../../../assets/cuts/crystal-four/5x5/0.json") as BakedCut, require("../../../../assets/cuts/crystal-four/5x5/1.json") as BakedCut, require("../../../../assets/cuts/crystal-four/5x5/2.json") as BakedCut, require("../../../../assets/cuts/crystal-four/5x5/3.json") as BakedCut, require("../../../../assets/cuts/crystal-four/5x5/4.json") as BakedCut, require("../../../../assets/cuts/crystal-four/5x5/5.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-four/5x5/6.json") as BakedCut, require("../../../../assets/cuts/crystal-four/5x5/7.json") as BakedCut],
    "7x7": [require("../../../../assets/cuts/crystal-four/7x7/0.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-four/7x7/1.json") as BakedCut, require("../../../../assets/cuts/crystal-four/7x7/2.json") as BakedCut, require("../../../../assets/cuts/crystal-four/7x7/3.json") as BakedCut],
  },
  "crystal-six": {
    "10x10": [require("../../../../assets/cuts-v2/crystal-six/10x10/0.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-six/10x10/1.json") as BakedCut],
    "14x14": [require("../../../../assets/cuts-v2/crystal-six/14x14/0.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-six/14x14/1.json") as BakedCut],
    "3x3": [require("../../../../assets/cuts/crystal-six/3x3/0.json") as BakedCut, require("../../../../assets/cuts/crystal-six/3x3/1.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-six/3x3/2.json") as BakedCut, require("../../../../assets/cuts/crystal-six/3x3/3.json") as BakedCut, require("../../../../assets/cuts/crystal-six/3x3/4.json") as BakedCut, require("../../../../assets/cuts/crystal-six/3x3/5.json") as BakedCut, require("../../../../assets/cuts/crystal-six/3x3/6.json") as BakedCut, require("../../../../assets/cuts/crystal-six/3x3/7.json") as BakedCut],
    "4x4": [require("../../../../assets/cuts/crystal-six/4x4/0.json") as BakedCut, require("../../../../assets/cuts/crystal-six/4x4/1.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-six/4x4/2.json") as BakedCut, require("../../../../assets/cuts/crystal-six/4x4/3.json") as BakedCut, require("../../../../assets/cuts/crystal-six/4x4/4.json") as BakedCut, require("../../../../assets/cuts/crystal-six/4x4/5.json") as BakedCut, require("../../../../assets/cuts/crystal-six/4x4/6.json") as BakedCut, require("../../../../assets/cuts/crystal-six/4x4/7.json") as BakedCut],
    "5x5": [require("../../../../assets/cuts/crystal-six/5x5/0.json") as BakedCut, require("../../../../assets/cuts/crystal-six/5x5/1.json") as BakedCut, require("../../../../assets/cuts/crystal-six/5x5/2.json") as BakedCut, require("../../../../assets/cuts/crystal-six/5x5/3.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-six/5x5/4.json") as BakedCut, require("../../../../assets/cuts/crystal-six/5x5/5.json") as BakedCut, require("../../../../assets/cuts/crystal-six/5x5/6.json") as BakedCut, require("../../../../assets/cuts/crystal-six/5x5/7.json") as BakedCut],
    "7x7": [require("../../../../assets/cuts/crystal-six/7x7/0.json") as BakedCut, require("../../../../assets/cuts/crystal-six/7x7/1.json") as BakedCut, require("../../../../assets/cuts-v2/crystal-six/7x7/2.json") as BakedCut, require("../../../../assets/cuts/crystal-six/7x7/3.json") as BakedCut],
  },
  "living-fringe": {
    "10x10": [require("../../../../assets/cuts-v2/living-fringe/10x10/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-fringe/10x10/1.json") as BakedCut],
    "14x14": [require("../../../../assets/cuts-v2/living-fringe/14x14/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-fringe/14x14/1.json") as BakedCut],
    "3x3": [require("../../../../assets/cuts/living-fringe/3x3/0.json") as BakedCut, require("../../../../assets/cuts/living-fringe/3x3/1.json") as BakedCut, require("../../../../assets/cuts/living-fringe/3x3/2.json") as BakedCut, require("../../../../assets/cuts-v2/living-fringe/3x3/3.json") as BakedCut, require("../../../../assets/cuts/living-fringe/3x3/4.json") as BakedCut, require("../../../../assets/cuts/living-fringe/3x3/5.json") as BakedCut, require("../../../../assets/cuts/living-fringe/3x3/6.json") as BakedCut, require("../../../../assets/cuts/living-fringe/3x3/7.json") as BakedCut],
    "4x4": [require("../../../../assets/cuts/living-fringe/4x4/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-fringe/4x4/1.json") as BakedCut, require("../../../../assets/cuts/living-fringe/4x4/2.json") as BakedCut, require("../../../../assets/cuts/living-fringe/4x4/3.json") as BakedCut, require("../../../../assets/cuts/living-fringe/4x4/4.json") as BakedCut, require("../../../../assets/cuts/living-fringe/4x4/5.json") as BakedCut, require("../../../../assets/cuts/living-fringe/4x4/6.json") as BakedCut, require("../../../../assets/cuts/living-fringe/4x4/7.json") as BakedCut],
    "5x5": [require("../../../../assets/cuts/living-fringe/5x5/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-fringe/5x5/1.json") as BakedCut, require("../../../../assets/cuts/living-fringe/5x5/2.json") as BakedCut, require("../../../../assets/cuts-v2/living-fringe/5x5/3.json") as BakedCut, require("../../../../assets/cuts/living-fringe/5x5/4.json") as BakedCut, require("../../../../assets/cuts/living-fringe/5x5/5.json") as BakedCut, require("../../../../assets/cuts/living-fringe/5x5/6.json") as BakedCut, require("../../../../assets/cuts/living-fringe/5x5/7.json") as BakedCut],
    "7x7": [require("../../../../assets/cuts/living-fringe/7x7/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-fringe/7x7/1.json") as BakedCut, require("../../../../assets/cuts/living-fringe/7x7/2.json") as BakedCut, require("../../../../assets/cuts/living-fringe/7x7/3.json") as BakedCut],
  },
  "living-spectrum": {
    "10x10": [require("../../../../assets/cuts-v2/living-spectrum/10x10/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/10x10/1.json") as BakedCut],
    "14x14": [require("../../../../assets/cuts-v2/living-spectrum/14x14/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/14x14/1.json") as BakedCut],
    "3x3": [require("../../../../assets/cuts/living-spectrum/3x3/0.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/3x3/1.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/3x3/2.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/3x3/3.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/3x3/4.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/3x3/5.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/3x3/6.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/3x3/7.json") as BakedCut],
    "4x4": [require("../../../../assets/cuts/living-spectrum/4x4/0.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/4x4/1.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/4x4/2.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/4x4/3.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/4x4/4.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/4x4/5.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/4x4/6.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/4x4/7.json") as BakedCut],
    "5x5": [require("../../../../assets/cuts/living-spectrum/5x5/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/5x5/1.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/5x5/2.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/5x5/3.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/5x5/4.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/5x5/5.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/5x5/6.json") as BakedCut, require("../../../../assets/cuts/living-spectrum/5x5/7.json") as BakedCut],
    "7x7": [require("../../../../assets/cuts/living-spectrum/7x7/0.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/7x7/1.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/7x7/2.json") as BakedCut, require("../../../../assets/cuts-v2/living-spectrum/7x7/3.json") as BakedCut],
  },
};
